"use client";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode, useEffect } from "react";
import "./globals.css";
import Header from "@/components/guest/Header";
import Footer from "@/components/guest/Footer";
import { Provider } from "react-redux";
import { store } from "@/app/store";
import { Providers } from "./providers";
import { usePathname } from "next/navigation";
import { PHASE_DEVELOPMENT_SERVER } from "next/dist/shared/lib/constants";
import HeaderAdmin from "@/components/admin/HeaderAdmin";
import { ToastContainer,Slide } from "react-toastify";
import { useAppDispatch } from "./hooks";
import { fetchProductFromApi } from "@/slice/ProductSlice";
import { fetchApiCart } from "@/slice/CartSlice";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: ReactNode }) {
  const pathname = usePathname();
  console.log("path name: ", pathname);
  
  return (
    <html
      lang="en"
      className={`${pathname.includes("/Admin") ? "overflow-y-hidden" : ""}`}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Slide}
        />
        <Providers>
          {pathname.includes("/Admin") ? <HeaderAdmin /> : <Header />}
          {children}
          {pathname.includes("/Admin") || pathname.includes("/Chat") ? "" : <Footer />}
        </Providers>
      </body>
    </html>
  );
}
